2018-09-26T04:37:16.930+0530 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] MongoDB starting : pid=97123 port=27017 dbpath=/data/db 64-bit host=C02Q46N5FVH7
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] db version v4.0.2
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] allocator: system
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] modules: none
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] build environment:
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten]     distarch: x86_64
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten]     target_arch: x86_64
2018-09-26T04:37:16.978+0530 I CONTROL  [initandlisten] options: {}
2018-09-26T04:37:16.982+0530 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-09-26T04:37:16.983+0530 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3584M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-09-26T04:37:17.966+0530 I STORAGE  [initandlisten] WiredTiger message [1537916837:966828][97123:0x7fff998fd380], txn-recover: Main recovery loop: starting at 14/8192
2018-09-26T04:37:17.967+0530 I STORAGE  [initandlisten] WiredTiger message [1537916837:967463][97123:0x7fff998fd380], txn-recover: Recovering log 14 through 15
2018-09-26T04:37:18.056+0530 I STORAGE  [initandlisten] WiredTiger message [1537916838:56091][97123:0x7fff998fd380], txn-recover: Recovering log 15 through 15
2018-09-26T04:37:18.121+0530 I STORAGE  [initandlisten] WiredTiger message [1537916838:121639][97123:0x7fff998fd380], txn-recover: Set global recovery timestamp: 0
2018-09-26T04:37:18.366+0530 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] 
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] 
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-09-26T04:37:18.453+0530 I CONTROL  [initandlisten] 
2018-09-26T04:37:18.581+0530 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-09-26T04:37:18.586+0530 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-09-26T04:37:19.013+0530 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK

> tiny-url@0.0.0 start /Users/milan.george/kubernetes-project/tinyUrl
> node ./bin/www

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/milan.george/kubernetes-project/tinyUrl/bin/www:8:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-url@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-url@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/milan.george/.npm/_logs/2018-09-25T23_07_27_410Z-debug.log
